services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres123"
    ports:
      - "5432:5432"
    volumes:
      - /home/samuelnfavero/Documentos/postgres
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "samuelnfavero@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge