server:
  port: 8100

spring:
  application:
    name: book-service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    schemas: public
    user: postgres
    password: postgres123

cambio-service:
  url: http://localhost:8000/cambio-service